# Generated by Django 6.0.2 on 2026-02-26 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VIDEO', '영상'), ('DOCUMENT', '문서'), ('LINK', '링크')], max_length=10, verbose_name='유형')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('publish_status', models.CharField(choices=[('DRAFT', '초안'), ('REVIEW', '검토중'), ('PUBLISHED', '게시됨'), ('ARCHIVED', '보관')], default='DRAFT', max_length=10, verbose_name='게시 상태')),
                ('view_scope', models.CharField(choices=[('ALL_USERS', '전체 공개'), ('ADMIN_ONLY', '관리자만'), ('CUSTOM', '커스텀')], default='ALL_USERS', max_length=12, verbose_name='열람 범위')),
                ('download_allowed', models.BooleanField(default=False, verbose_name='다운로드 허용')),
                ('security_label', models.CharField(blank=True, choices=[('L1', 'L1 - 공개'), ('L2', 'L2 - 사내'), ('L3', 'L3 - 대외비'), ('L4', 'L4 - 극비')], default='L2', max_length=2, verbose_name='보안 등급')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField(verbose_name='버전 번호')),
                ('source_type', models.CharField(choices=[('GDRIVE', 'Google Drive'), ('URL', 'URL 링크')], max_length=6, verbose_name='소스 유형')),
                ('source_url', models.URLField(max_length=1000, verbose_name='소스 URL')),
                ('source_file_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Drive 파일 ID')),
                ('note', models.TextField(blank=True, default='', verbose_name='변경 노트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_versions',
                'ordering': ['-version_no'],
                'unique_together': {('asset', 'version_no')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='latest_version',
            field=models.OneToOneField(blank=True, db_column='latest_version_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.assetversion'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.category'),
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.tag')),
            ],
            options={
                'db_table': 'asset_tags',
                'unique_together': {('asset', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', through='assets.AssetTag', to='assets.tag'),
        ),
        migrations.CreateModel(
            name='AssetPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('USER', '사용자'), ('DEPT', '부서'), ('ROLE', '역할')], max_length=4, verbose_name='대상 유형')),
                ('subject_id', models.CharField(max_length=200, verbose_name='대상 ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='열람 허용')),
                ('can_download', models.BooleanField(default=False, verbose_name='다운로드 허용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_permissions',
                'indexes': [models.Index(fields=['asset', 'subject_type'], name='idx_perm_asset_subj')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['type'], name='idx_assets_type'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['publish_status'], name='idx_assets_pub_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-updated_at'], name='idx_assets_updated'),
        ),
    ]
