# Generated by Django 6.0.2 on 2026-02-26 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='요청 사유')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('CANCELLED', '취소')], default='PENDING', max_length=10, verbose_name='상태')),
                ('comment', models.TextField(blank=True, default='', verbose_name='승인/반려 코멘트')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='assets.asset')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_share_req_status')],
            },
        ),
    ]
