# Generated by Django 6.0.2 on 2026-02-26 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 시간')),
                ('action', models.CharField(choices=[('VIEW', '열람'), ('DOWNLOAD', '다운로드'), ('PLAY', '재생'), ('SEARCH', '검색'), ('EXPORT_LOG', '로그 내보내기'), ('DENIED', '접근 거부')], max_length=12, verbose_name='액션')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('result', models.CharField(choices=[('SUCCESS', '성공'), ('DENIED', '거부'), ('FAIL', '실패')], default='SUCCESS', max_length=7, verbose_name='결과')),
                ('meta_json', models.JSONField(blank=True, null=True, verbose_name='메타 정보')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='assets.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='idx_log_occurred'), models.Index(fields=['action'], name='idx_log_action'), models.Index(fields=['user'], name='idx_log_user')],
            },
        ),
    ]
